import type { Skill, SkillGroup } from "./types";
import { FaSalesforce } from "react-icons/fa";
import {
  SiCss,
  SiFlutter,
  SiHtml5,
  SiJavascript,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiOpenjdk,
  SiPostgresql,
  SiPython,
  SiR,
  SiReact,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
} from "react-icons/si";

export const skillGroups = [
  { id: "interface", label: "Interface" },
  { id: "systems", label: "Systems" },
  { id: "data-ai", label: "Data and AI" },
  { id: "tools-delivery", label: "Tools and delivery" },
] as const satisfies readonly SkillGroup[];

// order still drives the materialize/dematerialize sequence in
// pc-sequence-section.tsx — untouched by the ring rework, ring is purely
// about where an icon orbits, not when it appears.
export const skills = [
  {
    id: "react",
    group: "interface",
    proof: {
      text: "I used React for PokeSim and WatchWise AI.",
      source: "Portfolio project stacks",
    },
    ownerInputs: [],
    name: "React",
    icon: SiReact,
    color: "#61DAFB",
    ring: 1,
    order: 1,
  },
  {
    id: "typescript",
    group: "interface",
    proof: {
      text: "I used TypeScript for Archive, WatchWise AI, and this portfolio.",
      source: "Portfolio project stacks",
    },
    ownerInputs: [],
    name: "TypeScript",
    icon: SiTypescript,
    color: "#3178C6",
    ring: 1,
    order: 2,
  },
  {
    id: "nextjs",
    group: "interface",
    proof: {
      text: "I built Forge and my previous portfolio with Next.js.",
      source: "README.md and portfolio project stacks",
    },
    ownerInputs: [],
    name: "Next.js",
    icon: SiNextdotjs,
    color: "#FFFFFF",
    ring: 1,
    order: 3,
  },
  {
    id: "javascript",
    group: "interface",
    proof: {
      text: "Forge uses a JavaScript fluid simulation.",
      source: "src/lib/fluid/fluid.js",
    },
    ownerInputs: [],
    name: "JavaScript",
    icon: SiJavascript,
    color: "#F7DF1E",
    ring: 2,
    order: 4,
  },
  {
    id: "nodejs",
    group: "systems",
    proof: {
      text: "Forge uses Node.js for its Next.js runtime and build tools.",
      source: "README.md and package.json",
    },
    ownerInputs: [],
    name: "Node.js",
    icon: SiNodedotjs,
    color: "#5FA04E",
    ring: 1,
    order: 5,
  },
  {
    id: "java",
    group: "systems",
    proof: null,
    ownerInputs: ["proof"],
    name: "Java",
    icon: SiOpenjdk,
    color: "#F89820",
    ring: 2,
    order: 6,
  },
  {
    id: "python",
    group: "data-ai",
    proof: {
      text: "I used Python for PokeSim and Smart Foot Traffic.",
      source: "Portfolio project stacks",
    },
    ownerInputs: [],
    name: "Python",
    icon: SiPython,
    color: "#3776AB",
    ring: 1,
    order: 7,
  },
  {
    id: "mysql",
    group: "data-ai",
    proof: null,
    ownerInputs: ["proof"],
    name: "MySQL",
    icon: SiMysql,
    color: "#4479A1",
    ring: 2,
    order: 8,
  },
  {
    id: "tailwindcss",
    group: "interface",
    proof: {
      text: "I used Tailwind for WatchWise AI and my portfolio.",
      source: "Portfolio project stacks",
    },
    ownerInputs: [],
    name: "Tailwind CSS",
    icon: SiTailwindcss,
    color: "#06B6D4",
    ring: 1,
    order: 9,
  },
  {
    id: "flutter",
    group: "interface",
    proof: {
      text: "I shipped Flutter features during my software development internship.",
      source: "src/lib/experience/experience-data.ts",
    },
    ownerInputs: [],
    name: "Flutter",
    icon: SiFlutter,
    color: "#02569B",
    ring: 2,
    order: 10,
  },
  {
    id: "postgresql",
    group: "data-ai",
    proof: null,
    ownerInputs: ["proof"],
    name: "PostgreSQL",
    icon: SiPostgresql,
    color: "#4169E1",
    ring: 2,
    order: 11,
  },
  {
    id: "html5",
    group: "interface",
    proof: {
      text: "I use semantic HTML for Forge's sections and forms.",
      source: "src/components/sections/contact-section.tsx",
    },
    ownerInputs: [],
    name: "HTML5",
    icon: SiHtml5,
    color: "#E34F26",
    ring: 2,
    order: 12,
  },
  {
    id: "supabase",
    group: "data-ai",
    proof: null,
    ownerInputs: ["proof"],
    name: "Supabase",
    icon: SiSupabase,
    color: "#3FCF8E",
    ring: 2,
    order: 13,
  },
  {
    id: "vercel",
    group: "tools-delivery",
    proof: {
      text: "My PokeSim and WatchWise AI demos have Vercel links.",
      source: "Portfolio project links",
    },
    ownerInputs: [],
    name: "Vercel",
    icon: SiVercel,
    color: "#FFFFFF",
    ring: 2,
    order: 14,
  },
  {
    id: "css",
    group: "interface",
    proof: {
      text: "I built Forge's fluid typography and spacing with CSS.",
      source: "src/styles/tokens.css",
    },
    ownerInputs: [],
    name: "CSS3",
    icon: SiCss,
    color: "#663399",
    ring: 2,
    order: 15,
  },
  {
    id: "salesforce",
    group: "tools-delivery",
    proof: null,
    ownerInputs: ["proof"],
    name: "Salesforce",
    icon: FaSalesforce,
    color: "#00A1E0",
    ring: 2,
    order: 16,
  },
  {
    id: "r",
    group: "data-ai",
    proof: null,
    ownerInputs: ["proof"],
    name: "R",
    icon: SiR,
    color: "#276DC3",
    ring: 2,
    order: 17,
  },
] as const satisfies readonly Skill[];

// next and vercel ship pure black marks that vanish here, so their badges go
// white and the icon renders in its own brand colour against the dark tint.
export const SKILL_COUNT = skills.length;

export const groupedSkills = skillGroups.map((group) => ({
  ...group,
  skills: skills.filter((skill) => skill.group === group.id),
}));
